### ISSUE TITLE
Can't change manually endpoints for api/smtp

### ISSUE THREAD

**Issue by pajics** [advancedrei/sendgridplus-csharp#13]
public const String BaseUrl = "sendgrid.com";
I cant change this if there is a need, so I would have to wait for you which is not really an option.

**Comment by robertmclaws** [comment]
I'll keep an eye on this in the future, but for now, because the API is specific to SendGrid, and they aren't gonna change their name anytime soon, I don't think it is necessary to implement this.

Thanks though!
