### ISSUE TITLE
EventData Serialization

### ISSUE THREAD

**Issue by toazjason** [advancedrei/sendgridplus-csharp#15]
Performing a Serialization operation on the EventData object is failing 
I tested this using the Newtonsoft.Json package JsonConvert.SerializeObject gives an the error "The method or operation is not implemented.".

Please add serialization support for this class.

**Comment by robertmclaws** [comment]
Hmm. I can add that, but what is the scenario where you are trying to re-serialize the event?

**Comment by toazjason** [comment]
We are implementing WebHook Events and because of the large amount of processing this can cause we are putting the event data into an Azure Message Queue for later bulk processing to the database.  However before we do that I need to call GetEvents to evaluation the type of events I want to queue.

So the plan is to call GetEvents, evaluate the event type, then if its one we handle, to serialize it to a Json string for storage in the queue and then deserialize it again when we process the queue in bulk.

**Comment by toazjason** [comment]
Update: I discovered that the EventData is not serializing properly when there is a value in the Categories collection.  Otherwise it serializes just fine.

**Comment by toazjason** [comment]
Another issue is that the Categories collection returns null when there is no category passed in.  It should be instantiated and allow us to call Count on it to determine if it has any entries.

**Comment by robertmclaws** [comment]
I put out an update that takes care of both the Categories and the general serialization issue. Please let me know if you have any further problems!
