### ISSUE TITLE
Events static methods only works with batched events

### ISSUE THREAD

**Issue by siewers** [advancedrei/sendgridplus-csharp#2]
Hi,

when using the EventAPI, the POST from batched events are handled correctly. Without batched events enabled, the POST does not contain JSON, making the Events static methods throw an exception.

**Comment by robertmclaws** [comment]
If you do not have Batched Events enabled, you can use the static GetEvent() command in the same manner, and it will work properly.

Also, if you log into your account, you can now select which version of the API you want to use. V3 defaults to batched events.

**Comment by robertmclaws** [comment]
FYI, I just published SendGridPlus v3 to NuGet, which handles the new v3 of the API, which defaults to batched mode.
