### ISSUE TITLE
GetEvents (Batch) not working properly

### ISSUE THREAD

**Issue by GenGol** [advancedrei/sendgridplus-csharp#4]
The old code worked great.  However, back in September 2013 they introduced their new POST method.  I'm trying to use the new version of this library, but it fails.  I'm testing using their TEST data they provide.  Here is the json they are sending:

[{"email":"john.doe@sendgrid.com","timestamp":1337197600,"smtp-id":"4FB4041F.6080505@sendgrid.com","event":"processed"},{"email":"john.doe@sendgrid.com","timestamp":1337966815,"smtp-id":"4FBFC0DD.5040601@sendgrid.com","category":"newuser","event":"processed"},{"email":"john.doe@sendgrid.com","timestamp":1337969592,"smtp-id":"20120525181309.C1A9B40405B3@Mohammeds-Mac.local","event":"processed"},{"email":"bill.nye@thescienceguy.com","timestamp":1337971272,"smtp-id":"20120525184109.9578F40409A5@Mohammeds-Mac.local","reason":"Unsubscribed Address","event":"dropped"},{"email":"bill.nye@thescienceguy.com","timestamp":1337979680,"smtp-id":"20120525210118.7F3724041B6D@Mohammeds-Mac.local","reason":"Unsubscribed Address","event":"dropped"},{"email":"bill.nye@thescienceguy.com","timestamp":1337980426,"smtp-id":"20120525211344.2844C4041EB2@Mohammeds-Mac.local","reason":"Unsubscribed Address","event":"dropped"},{"email":"iamemail@gmail.com","attempt":"17","smtp-id":"4FB29F5D.5080404@sendgrid.com","timestamp":1337201407,"response":"501 Syntax error - Badly formatted address. ","event":"deferred"},{"email":"iamemail@gmail.com","attempt":"18","smtp-id":"4FB29F5D.5080404@sendgrid.com","timestamp":1337212247,"response":"Connection timed out","event":"deferred"},{"email":"iamemail@gmail.com","attempt":"25","smtp-id":"4FB29F5D.5080404@sendgrid.com","timestamp":1337288707,"response":"501 Syntax error - Badly formatted address. ","event":"deferred"},{"email":"john.doe@sendgrid.com","smtp-id":"4FBFC0DD.5040601@sendgrid.com","timestamp":1337966817,"response":"250 2.0.0 OK 1337966817 z9si3846029icy.10 ","category":"newuser","event":"delivered"},{"email":"john.doe@sendgrid.com","smtp-id":"20120525183816.12AA6404092A@Mohammeds-Mac.local","timestamp":1337971099,"response":"250 2.0.0 OK 1337971099 l10si4052001icz.31 ","event":"delivered"},{"email":"foobar@yahoo.com","smtp-id":"20120525183951.59BEA4040968@Mohammeds-Mac.local","timestamp":1337971198,"response":"250 2.0.0 OK 1337971198 xz10si2239282obb.108 ","event":"delivered"},{"email":"foobar@yahoo.com","smtp-id":"20120525181029.220EE404043A@Mohammeds-Mac.local","timestamp":1337969434,"status":"5.1.1","reason":"550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at http://support.google.com/mail/bin/answer.py?answer=6596 z6si25868142igk.15 ","type":"bounce","event":"bounce"},{"email":"john.doe@sendgrid.com","timestamp":1338574236,"url":"http://www.sendgrid.com","event":"click"},{"email":"john.doe@sendgrid.com","timestamp":1338572978,"url":"http://www.sendgrid.com","event":"click"},{"email":"john.doe@sendgrid.com","timestamp":1338595596,"url":"http://www.sendgrid.com","event":"click"},{"email":"john.doe@sendgrid.com","timestamp":1338312226,"newsletter":{"newsletter_user_list_id":"1695412","newsletter_id":"310318","newsletter_send_id":"425605"},"category":["dsfdsf","Newsletter"],"event":"open"},{"email":"john.doe@sendgrid.com","timestamp":1338487320,"event":"open"},{"email":"john.doe@sendgrid.com","timestamp":1338578578,"event":"open"},{"email":"john.doe@sendgrid.com","timestamp":1340126539,"newsletter":{"newsletter_user_list_id":"1695412","newsletter_send_id":"478915","newsletter_id":"428128"},"category":["TESTt","Newsletter"],"event":"unsubscribe"},{"email":"john.doe@sendgrid.com","timestamp":1338310756,"newsletter":{"newsletter_user_list_id":"1695100","newsletter_send_id":"425584","newsletter_id":"331537"},"category":["TEST","Newsletter"],"event":"unsubscribe"},{"email":"john.doe@sendgrid.com","timestamp":1340126539,"newsletter":{"newsletter_user_list_id":"1695412","newsletter_send_id":"478915","newsletter_id":"428128"},"category":["TESTt","Newsletter"],"event":"unsubscribe"},{"email":"mysendgriid@hotmail.com","event":"spamreport","timestamp":1347307636,"category":["board_collaborator_new_pin"],"unique_args":{"tracking_id":"c99z72cd5537515d9b0e3d8cab1ec09e","time_sent":1346814447,"sender_username":"notasendr","recipient_username":"realusername"}}]

The library blows up in public static List<SendGridEventData> GetEvents(string json) with the following error:

Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'SignupMadeEasy.Utilies.SendGridEventData' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '[0]', line 1, position 2.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)

I've seen messages on the board that their JSON object is not valid.  Any suggestions on fixing this?

**Comment by GenGol** [comment]
I made the change to the following by commenting out the string.Format....

public static List<SendGridEventData> GetEvents(string json)
        {
            // removed 2013-09-11 for Version 3 of SendGrid Events
            //json = string.Format("[{0}]", json.Replace("}" + Environment.NewLine + "{", "},{"));
            return JsonConvert.DeserializeObject<List<SendGridEventData>>(json);
        }

This fixed the issue.  However, there is still an issue with "Category" that sendgrid is formatting.  They are sending it in two different formats:

"category":"newuser","event":"processed" 
 "category":["dsfdsf","Newsletter"] 

I posted this in their community forums where I found your original post (http://community.sendgrid.com/sendgrid/topics/batched_events_dont_seem_to_send_valid_json) about your library (thank you very much) about the category issue.  Perhaps you have a work around in your library for it?  Thank you for your help.

**Comment by robertmclaws** [comment]
FYI, I just published SendGridPlus 3.0 on NuGet, which fixes this issue, as well as handles other issues SendGrid has with creating syntactically-valid JSON. https://www.nuget.org/packages/SendGridPlus. Handles all three versions of the Event API silently. HTH.

**Comment by GenGol** [comment]
Great, thank you for the update.
