### ISSUE TITLE
Need to specify content type for embedded attachments

### ISSUE THREAD

**Issue by HakanL** [advancedrei/sendgridplus-csharp#6]
I'm trying to add embedded images in an email and I can't find a way to add the content type on these images. It seems they are added as octet type, which only works in some email clients.

**Comment by robertmclaws** [comment]
I'll see what I can do.

**Comment by HakanL** [comment]
I started to make changes for this in my fork: https://github.com/HakanL/sendgridplus-csharp, testing it now.

**Comment by robertmclaws** [comment]
Good deal, lemme know how it works out, and feel free to make a pull request. I'll look into making the methods Async this weekend.

**Comment by HakanL** [comment]
I think it's working fine now, I can get embedded images. I'll do a few more tests and then do a pull request.

**Comment by robertmclaws** [comment]
Fantastic, thanks so much for all of your efforts :)

**Comment by HakanL** [comment]
Of course, my pleasure!
